normalization_scheme = {'А': 'A',
                        'Б': 'B',
                        'В': 'V',
                        'Г': 'H',
                        'Д': 'D',
                        'Е': 'E',
                        'Ё': 'E',
                        'Ж': 'ZH',
                        'З': 'Z',
                        'И': 'Y',
                        'Й': 'Y',
                        'К': 'K',
                        'Л': 'L',
                        'М': 'M',
                        'Н': 'N',
                        'О': 'O',
                        'П': 'P',
                        'Р': 'R',
                        'С': 'S',
                        'Т': 'T',
                        'У': 'U',
                        'Ф': 'F',
                        'X': 'KH',
                        'Ц': 'TS',
                        'Ч': 'CH',
                        'Ш': 'SH',
                        'Щ': 'SHCH',
                        'Ы': 'I',
                        'Э': 'E',
                        'Ю': 'YU',
                        'Я': 'YA',
                        'Ґ': 'G',
                        'Є': 'IE',
                        'Ї': 'YI',
                        'а': 'a',
                        'б': 'в',
                        'в': 'v',
                        'г': 'h',
                        'д': 'd',
                        'е': 'e',
                        'ё': 'e',
                        'ж': 'zн',
                        'з': 'z',
                        'и': 'y',
                        'й': 'y',
                        'к': 'к',
                        'л': 'l',
                        'м': 'm',
                        'н': 'n',
                        'о': 'o',
                        'п': 'p',
                        'р': 'r',
                        'с': 's',
                        'т': 't',
                        'у': 'u',
                        'ф': 'f',
                        'x': 'kh',
                        'ц': 'ts',
                        'ч': 'ch',
                        'ш': 'sн',
                        'щ': 'shch',
                        'ы': 'i',
                        'э': 'e',
                        'ю': 'yu',
                        'я': 'ya',
                        'ґ': 'g',
                        'є': 'ie',
                        'ї': 'yi',
                        'A': 'A',
                        'B': 'B',
                        'C': 'C',
                        'D': 'D',
                        'E': 'E',
                        'F': 'F',
                        'G': 'G',
                        'H': 'H',
                        'I': 'I',
                        'J': 'J',
                        'K': 'K',
                        'L': 'L',
                        'M': 'M',
                        'N': 'N',
                        'O': 'O',
                        'P': 'P',
                        'Q': 'Q',
                        'R': 'R',
                        'S': 'S',
                        'T': 'T',
                        'U': 'U',
                        'V': 'V',
                        'W': 'W',
                        'X': 'X',
                        'Y': 'Y',
                        'Z': 'Z',
                        'a': 'a',
                        'b': 'b',
                        'c': 'c',
                        'd': 'd',
                        'e': 'e',
                        'f': 'f',
                        'g': 'g',
                        'h': 'h',
                        'i': 'i',
                        'j': 'j',
                        'k': 'k',
                        'l': 'l',
                        'm': 'm',
                        'n': 'n',
                        'o': 'o',
                        'p': 'p',
                        'q': 'q',
                        'r': 'r',
                        's': 's',
                        't': 't',
                        'u': 'u',
                        'v': 'v',
                        'w': 'w',
                        'x': 'x',
                        'y': 'y',
                        'z': 'z',
                        '0': '0',
                        '1': '1',
                        '2': '2',
                        '3': '3',
                        '4': '4',
                        '5': '5',
                        '6': '6',
                        '7': '7',
                        '8': '8',
                        '9': '9'
                        }

def normalize(norm_name: str):
    """
    to normalized string with transliteration
    incoming: File/folder object name - string, the current file object - Path
    out (return): normalized name - string
    """
    normalized = ''
    for v_symbol in norm_name:
        # unknown symbols into "_" :
        normalized += normalization_scheme.get(v_symbol, '_')
    return str(normalized)  # new transliteration name (str out)
